version: '3.9'

services:
  postgres:
    image: postgres:14
    container_name: OnlineAppDB
    restart: unless-stopped
    environment:
      POSTGRES_USER: springuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mainDB
      TZ: Asia/Ho_Chi_Minh
    volumes:
      - onlineDB_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U springuser -d mainDB"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2
    container_name: redis-DB
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisDB_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  onlineDB_data:
  redisDB_data:
