version: '3.9'

services:
  postgres:
    image: postgres:14
    container_name: OnlineAppDB
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: mainDB
      TZ: Asia/Ho_Chi_Minh
    volumes:
      - onlineDB_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U springuser -d mainDB"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2
    container_name: redis-DB
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisDB_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: mainDB
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - node.name=es-node
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:9200/_cluster/health?wait_for_status=yellow || exit 1"
        ]
      interval: 7s
      timeout: 7s
      retries: 12

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: kibana
    restart: unless-stopped
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:5601/api/status || exit 1"
        ]
      interval: 10s
      timeout: 10s
      retries: 10

#  filebeat:
#    image: docker.elastic.co/beats/filebeat:8.11.1
#    container_name: filebeat
#    user: root
#    restart: unless-stopped
#    depends_on:
#      elasticsearch:
#        condition: service_healthy
#    volumes:
#      - ./logs:/logs
#      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
#    command: [ "--strict.perms=false" ]

volumes:
  onlineDB_data:
  redisDB_data:
  mongodb_data:
  es_data:
